tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "vitorgalvao/tiny-scripts"
brew "python@3.11"
brew "awscli"
brew "curl"
brew "docker", link: false
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gopass"
brew "gradle"
brew "gradle@6"
brew "hadolint"
brew "jenv"
brew "ktlint"
brew "mas"
brew "maven"
brew "node"
brew "shellcheck"
brew "spaceship"
brew "swiftlint"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-syntax-highlighting"
cask "1password"
cask "aerial"
cask "alt-tab"
cask "android-sdk"
cask "android-studio"
cask "bartender"
cask "discord"
cask "docker"
cask "eclipse-jee"
cask "firefox"
cask "flux"
cask "font-hack"
cask "google-chrome"
cask "google-chrome-canary"
cask "gpg-suite"
cask "iterm2"
cask "jd-gui"
cask "keepingyouawake"
cask "logitech-g-hub"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "microsoft-teams"
cask "notunes"
cask "postman"
cask "rectangle"
cask "rocket-chat"
cask "slack"
cask "spotify"
cask "temurin"
cask "temurin11"
cask "temurin8"
cask "unclack"
cask "visual-studio-code-insiders"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tampermonkey", id: 1482490089
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
